title: InfiOpen Template
url: "https://InfiOpen.github.io"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: Jekyll template with example content for a web agency.

# Author details for the jekyll-seo-tag gem
author:
  name: InfiOpen
  email: info@infiopen.com  
  twitter: InfiOpen

# Social details for the jekyll-seo-tag gem
social:
  name: InfiOpen web design and development services
  links:
    - https://InfiOpen.github.io

timezone: Etc/UTC

collections:
  staff_members:
    output: false
  clients:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

_select_data:
  social_icons:
    - Facebook
    - Instagram
    - LinkedIn
    - Pinterest
    - Tumblr
    - Twitter
    - YouTube
    - RSS
